[build-system]
requires = ["maturin==1.14"]
build-backend = "maturin"

[project]
name = "xensieve"
dynamic = ["version"]
description = "A Rust-backed implementation of the Xenakis Sieve"

authors = [{name = "Christopher Ariza"}]
maintainers = [{name = "Christopher Ariza"}]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Artistic Software",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Typing :: Typed",
]

keywords = ["sieve", "residual", "modulus", "set", "xenakis"]


[project.urls]
Homepage = "https://github.com/ampullator/xensieve-py"
Repository = "https://github.com/ampullator/xensieve-py.git"
Issues = "https://github.com/ampullator/xensieve-py/issues"

[tool.maturin]
features = ["pyo3/extension-module"]
